name: Task Management CI

on:
    workflow_dispatch:
    push:
        branches:
        - main

env:
  AZURE_WEBAPP_NAME: taskmanagement-app
  DOCKER_IMAGE_NAME: taskmanagement-app
  DOCKER_REGISTRY: taskmanagement.azurecr.io
  DOCKER_TAG: latest
    
jobs:             
                
    build-and-deploy-container:
        name: Build and deploy Docker container to Azure
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
                
            - name: Azure login (OIDC)
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                
            - name: Build Docker image
              run: |
                docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                docker push ${{env.DOCKER_REGISTRY}}
    